version: '2'
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    volumes:
      # put SQL files to /docker-entrypoint-initdb.d, they will be executed after DB is ready
      - "./db.sql:/docker-entrypoint-initdb.d/create_databases.sql"
