spring:
  datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
mybatis:
   mapperLocations: classpath:/mapper/*.xml

pacfile:
  server:
    url: http://47.114.176.127/
  folder:
    path: ${SERVER_PACFILE_PATH:/home/aaronhu/Documents/}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

server:
  port: ${SERVER_HTTP_PORT:8080}
